# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: gabrielkuettel@gmail.com
author_name: Gabriel Kuettel
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: algokit-hello-world

